#!/bin/bash
# Autor: Marcos Antonio de Carvalho
# Descrição: Instalação do Oh-my-bash para embelezamento

cd ~ || exit

#-- Header
echo "Ubuntu on WSL - Versao 1.0"
echo "2023 by Marcos Antonio de Carvalho"
echo "----------------------------------"
start=$(date +%s)
figlet WSL | lolcat

#  *************
#    FUNCTIONS
#  *************

# Instalação/Remoção Docker Containers
# Funções implementadas:
# package_remove() e package_install()
# docker_remove() e docker_install()
. ~/dream/k-FUNCTIONS

#  **********
#    DOCKER
#  **********

docker_install
# Teste: docker run hello-world

# inicializa o serviço docker
service docker start >/dev/null 2>&1

# Volumes
mkdir -p ~/volume/postgres
mkdir -p ~/volume/pgadmin
mkdir -p ~/volume/mysql
mkdir -p ~/volume/mediawiki/database
mkdir -p ~/volume/mediawiki/html/images

#  *************************************************************
#    WSL - Configuração de comandos para proxima inicialização
#  *************************************************************

# Configuração de comandos para proxima inicialização do WSL
# https://learn.microsoft.com/pt-br/windows/wsl/wsl-config

cat <<EOF >/mnt/c/Users/karvalho/teste.wslconfig
# Settings apply across all Linux distros running on WSL 2
[wsl2]

# Limits VM memory to use no more than 4 GB, this can be set as whole numbers using GB or MB
memory=4GB 

# Sets the VM to use two virtual processors
processors=2

EOF
echo "Created /mnt/c/Users/<UserName>/.wslconfig"

cat <<EOF >/etc/wsl.conf
#
# Configuração criada pelo setWSL
#
# Defina um comando para ser executado quando uma nova instância do WSL for iniciada.
[boot]
command = "service docker start"
#command = "service docker start; /opt/node_exporter/node_exporter &; echo Ok"

EOF
echo "Created /etc/wsl.conf"

#
# É necessário o comando 'wsl --shutdown' para recarregar o arquivo wsl.conf
#

#-- Runtime
echo
end=$(date +%s)
date
runtime=$((end - start))
echo "Runtime $runtime seconds"
echo ""
